### ISSUE TITLE
Testowa baza danych się buntuje

### ISSUE THREAD

**Issue by geodotka** [geodotka/ulicznicy#33]
python manage.py test
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/test/runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/test/runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/test/runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 377, in create_test_db
    test_flush=True,
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 179, in add_field
    self._remake_table(model, create_fields=[field])
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 139, in _remake_table
    self.create_model(temp_model)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 213, in create_model
    definition, extra_params = self.column_sql(model, field)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 116, in column_sql
    db_params = field.db_parameters(connection=self.connection)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 548, in db_parameters
    type_string = self.db_type(connection)
  File "/home/dorota/Envs/ulicznicy/local/lib/python2.7/site-packages/django/contrib/gis/db/models/fields.py", line 220, in db_type
    return connection.ops.geo_db_type(self)
AttributeError: 'DatabaseOperations' object has no attribute 'geo_db_type'

**Comment by geodotka** [comment]
@Cosiek, mogłabym to nazwac magią - zapuściłam przed chwilą testy i wszystko ładnie poszło. Zamykam natenczas zadanie, jeśłi sytuacja się powtórzy, reotworzę.
